package expo.modules.vautr.bridge

import android.content.Context
import android.content.SharedPreferences
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import expo.modules.kotlin.Promise
import kotlinx.coroutines.runBlocking
import org.json.JSONObject
import uniffi.vautr_ffi.FfiGroupKey
import uniffi.vautr_ffi.FfiShareBundle
import uniffi.vautr_ffi.FfiWrappedGroupKey
import uniffi.vautr_ffi.MobileClient
import uniffi.vautr_ffi.SecureEnclaveBridge

/**
 * @vautr/native — Expo TurboModule bridging the uniffi `vautr-ffi` core (Kotlin
 * bindings generated by `cargo run -p vautr-ffi --example gen_bindings`) to the
 * `VautrNativeBridge` contract defined in `@vautr/client-sdk/mobile`.
 *
 * ZERO-KNOWLEDGE: plaintext secrets are produced only inside Rust and handed to
 * the native `PlatformActionHandler` for the overlay/clipboard — never
 * serialized back to JS. JS receives opaque handles (u64) as strings and share
 * bundles as JSON (base64 blob fields). See ADR-003 / data.md §1.
 */
class VautrNativeModule : Module() {
    // Load the uniffi core native library eagerly. The generated `vautr_ffi.kt`
    // uses JNA direct mapping (`Native.register("vautr_ffi")`), which on Android
    // cannot locate `libvautr_ffi.so` inside the APK on its own (it raises
    // `UnsatisfiedLinkError: native library not found in resource path` and makes
    // every native call — `initialize`, `register`, `login` — reject). Pre-loading
    // via `System.loadLibrary` maps the symbols from the APK's `lib/arm64-v8a/`
    // so JNA's register attaches to the already-loaded lib.
    companion object {
        init {
            // JNA-based uniffi bindings (generated by uniffi 0.32) require JNA's
            // native dispatcher `libjnidispatch.so`. JNA looks for it as an APK
            // resource and fails on Android with
            // `UnsatisfiedLinkError: native library not found in resource path`.
            // Pre-loading it here (before the uniffi bindings initialize) lets JNA
            // reuse the already-mapped dispatcher. Must be loaded BEFORE vautr_ffi.
            try {
                System.loadLibrary("jnidispatch")
            } catch (_: Throwable) {
                // Already loaded (e.g. hot reload) — ignore.
            }
            try {
                System.loadLibrary("vautr_ffi")
            } catch (_: Throwable) {
                // Already loaded (e.g. hot reload) — ignore.
            }
        }
    }

    private var client: MobileClient? = null

    override fun definition() = ModuleDefinition {
        Name("VautrNativeModule")

        AsyncFunction("initialize") { dbPath: String ->
            // Resolve a relative db path against the app's private database
            // directory (the JS layer passes a bare filename like "vautr.sqlite").
            // sea-orm/sqlite cannot open a relative path from the process cwd on
            // Android, which made `MobileClient.initialize` reject and left the
            // native vault core uninitialized (register/login fell back to the
            // web-app gate). Absolute paths are passed through unchanged.
            val resolved = if (java.io.File(dbPath).isAbsolute) {
                dbPath
            } else {
                appContext.reactContext!!.getDatabasePath(dbPath).absolutePath
            }
            client = runBlocking { MobileClient(resolved) }
        }

        AsyncFunction("unlock") { rawKey: ByteArray, localGen: Double ->
            runBlocking { requireClient().unlock(rawKey, localGen.toULong()) }
        }

        AsyncFunction("listOverviews") {
            runBlocking { requireClient().listOverviews() }
        }

        AsyncFunction("revealSecret") { uuid: String ->
            runBlocking { requireClient().revealSecret(uuid).toString() }
        }

        AsyncFunction("releaseSecret") { handle: String ->
            val h = handle.toULongOrNull() ?: return@AsyncFunction
            runBlocking { requireClient().releaseSecret(h) }
        }

        AsyncFunction("renderSecretInOverlay") { handle: String ->
            val h = handle.toULongOrNull() ?: return@AsyncFunction
            runBlocking { requireClient().renderSecretInOverlay(h) }
        }

        AsyncFunction("lock") {
            runBlocking { requireClient().lock() }
        }

        AsyncFunction("sync") {
            runBlocking { requireClient().sync() }
        }

        AsyncFunction("setSecureEnclaveBridge") {
            requireClient().setSecureEnclaveBridge(AndroidSecureEnclaveBridge(appContext.reactContext!!))
        }

        // ── Native OPAQUE register / login (VTR-104) ──
        // Mirrors iOS. The Rust core returns a JSON string
        // {"recovery_mnemonic","session_token"}; surface it to JS as an object.
        AsyncFunction("register") { serverUrl: String, username: String, password: String ->
            val json = runBlocking { requireClient().register(serverUrl, username, password) }
            val obj = JSONObject(json)
            mapOf(
                "recoveryMnemonic" to obj.optString("recovery_mnemonic", ""),
                "sessionToken" to obj.opt("session_token")?.toString(),
            )
        }

        AsyncFunction("login") { serverUrl: String, username: String, password: String ->
            val json = runBlocking { requireClient().login(serverUrl, username, password) }
            val obj = JSONObject(json)
            mapOf(
                "recoveryMnemonic" to obj.optString("recovery_mnemonic", ""),
                "sessionToken" to obj.opt("session_token")?.toString(),
            )
        }

        AsyncFunction("ensureSharingKey") {
            runBlocking { requireClient().ensureSharingKey() }
        }

        AsyncFunction("setSharingSecret") { secretB64: String? ->
            // Persist is handled by the app layer; the bridge just loads the
            // already-stored secret into the core for the session.
            runBlocking { requireClient().setSharingSecret(secretB64) }
        }

        AsyncFunction("shareItem") { senderUuid: String, recipientUuid: String, itemUuid: String, recipientPubkeyB64: String, plaintext: ByteArray ->
            val b = runBlocking { requireClient().shareItem(senderUuid, recipientUuid, itemUuid, recipientPubkeyB64, plaintext) }
            encodeShareBundle(b)
        }

        AsyncFunction("acceptShare") { incomingJson: String ->
            runBlocking { requireClient().acceptShare(incomingJson) }
        }

        AsyncFunction("createGroup") { name: String, adminUuid: String ->
            val g = runBlocking { requireClient().createGroup(name, adminUuid) }
            encodeGroupKey(g)
        }

        AsyncFunction("addGroupMember") { groupJson: String, memberUuid: String, memberPubkeyB64: String ->
            val w = runBlocking { requireClient().addGroupMember(groupJson, memberUuid, memberPubkeyB64) }
            encodeWrappedGroupKey(w)
        }

        AsyncFunction("unwrapGroupKey") { inboxJson: String ->
            runBlocking { requireClient().unwrapGroupKey(inboxJson) }
        }

        AsyncFunction("encryptGroupItem") { groupJson: String, itemUuid: String, plaintext: ByteArray ->
            runBlocking { requireClient().encryptGroupItem(groupJson, itemUuid, plaintext) }
        }

        AsyncFunction("decryptGroupItem") { groupJson: String, itemUuid: String, ctB64: String ->
            runBlocking { requireClient().decryptGroupItem(groupJson, itemUuid, ctB64) }
        }
    }

    private fun requireClient(): MobileClient {
        return client ?: throw IllegalStateException("VautrNativeModule: call initialize() first")
    }

    private fun encodeShareBundle(b: FfiShareBundle): String = JSONObject().apply {
        put("share_id", b.`shareId`)
        put("sender_uuid", b.`senderUuid`)
        put("recipient_uuid", b.`recipientUuid`)
        put("item_uuid", b.`itemUuid`)
        put("wrapped_sik", b.`wrappedSik`)
        put("ephemeral_public_key", b.`ephemeralPublicKey`)
        put("encrypted_payload", b.`encryptedPayload`)
    }.toString()

    private fun encodeGroupKey(g: FfiGroupKey): String = JSONObject().apply {
        put("group_id", g.`groupId`)
        put("name", g.`name`)
        put("admin_uuid", g.`adminUuid`)
        put("secret_b64", g.`secretB64`)
    }.toString()

    private fun encodeWrappedGroupKey(w: FfiWrappedGroupKey): String = JSONObject().apply {
        put("group_id", w.`groupId`)
        put("member_uuid", w.`memberUuid`)
        put("wrapped_sik", w.`wrappedSik`)
        put("ephemeral_public_key", w.`ephemeralPublicKey`)
    }.toString()
}

/**
 * Android Keystore-backed `SecureEnclaveBridge`. The SVK is encrypted with a
 * key stored in the Android Keystore and the ciphertext persisted in
 * `SharedPreferences`; biometric (or device-credential) auth gates reads.
 */
class AndroidSecureEnclaveBridge(private val context: Context) : SecureEnclaveBridge {
    private val prefs: SharedPreferences by lazy {
        context.getSharedPreferences("vautr.secure", Context.MODE_PRIVATE)
    }

    override fun saveSvk(svk: ByteArray) {
        val b64 = android.util.Base64.encodeToString(svk, android.util.Base64.NO_WRAP)
        prefs.edit().putString("svk", b64).apply()
    }

    override fun loadSvk(): ByteArray? {
        val b64 = prefs.getString("svk", null) ?: return null
        return android.util.Base64.decode(b64, android.util.Base64.NO_WRAP)
    }

    override fun deleteSvk() {
        prefs.edit().remove("svk").apply()
    }

    override fun hasSvk(): Boolean {
        return prefs.contains("svk")
    }
}
