// @ts-nocheck
// Design-token generator for Vautr ("The Vault Ledger").
// Zero runtime deps. Reads the authored sources and emits platform outputs:
//   dist/tokens.css        -> consumed by apps/extension + apps/web (globals.css @import)
//   dist/tokens.rs         -> consumed by apps/desktop/src/theme.rs (re-export)
//   dist/tokens.ts         -> consumed by mobile/lib (NativeWind theme)
//   dist/vautr-theme.json  -> GPUI-component theme (apps/desktop/src/vautr-theme.json)
//   dist/tokens.md         -> human-readable swatches (docs)
//
// Source of truth: ../tokens.json (primitives, dark+light) + ../gpui-map.json
// (primitive -> GPUI semantic key assignment). Never hand-edit the dist/ files.
//
// Usage: node scripts/build.mjs            (write outputs)
//        node scripts/build.mjs --check    (assert outputs already match; CI gate)

import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/** Collapse all whitespace runs so formatter drift (cargo fmt / css reflow)
 *  does not cause a false token-drift failure. Token-value edits still differ. */
function normalizeWs(s) {
  return s.replace(/\s+/g, ' ').trim();
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const CHECK = process.argv.includes('--check');

const tokens = JSON.parse(readFileSync(join(ROOT, 'tokens.json'), 'utf8'));
const gpuiMap = JSON.parse(readFileSync(join(ROOT, 'gpui-map.json'), 'utf8'));

// --- resolve {group.name} references against tokens.json ---
function ref(path) {
  const [group, name] = path.replace(/[{}]/g, '').split('.');
  const node = tokens[group]?.[name];
  if (!node) throw new Error(`Unresolved token ref: ${path}`);
  return node;
}
function modeHex(node, mode) {
  const v = node.$value;
  if (typeof v === 'string') return v; // literal (e.g. scrollbar hex8)
  return v[mode];
}
function _isColor(group) {
  return group === 'color';
}

// --- CSS ---
// Explicit map: token path -> shadcn CSS var name used across web/extension
// (must match the names components already reference, so globals.css can drop
// its hand-typed block without touching any component).
const CSS_VAR = {
  'color.background': '--background',
  'color.foreground': '--foreground',
  'color.surface': '--card',
  'color.surface-raised': '--accent',
  'color.foreground-muted': '--muted-foreground',
  'color.foreground-dim': '--foreground-dim',
  'color.border': '--border',
  'color.input': '--input',
  'color.accent': '--primary',
  'color.accent-foreground': '--primary-foreground',
  'color.accent-dim': '--primary-dim',
  'color.danger': '--destructive',
  'color.danger-background': '--destructive-background',
  'color.danger-foreground': '--destructive-foreground',
  'color.warning': '--warning',
  'color.success': '--success',
  'color.popover': '--popover',
  'color.popover-foreground': '--popover-foreground',
  'color.sidebar': '--sidebar',
  'color.sidebar-foreground': '--sidebar-foreground',
  'color.sidebar-border': '--sidebar-border',
  'color.sidebar-primary': '--sidebar-primary',
  'color.sidebar-primary-foreground': '--sidebar-primary-foreground',
  'color.sidebar-accent': '--sidebar-accent',
  'color.sidebar-accent-foreground': '--sidebar-accent-foreground',
  'color.ring': '--ring',
  'color.chart-1': '--chart-1',
  'color.chart-2': '--chart-2',
  'color.chart-3': '--chart-3',
  'color.chart-4': '--chart-4',
  'color.chart-5': '--chart-5',
};

function buildCss() {
  const lines = [];
  lines.push('/* GENERATED by packages/design-tokens/scripts/build.mjs — do not edit. */');
  lines.push('/* Source of truth: tokens.json (dark + light). Imported by globals.css. */');
  lines.push('');
  const emitMode = (mode, selector) => {
    lines.push(`${selector} {`);
    for (const [group, leaves] of Object.entries(tokens)) {
      if (group.startsWith('$')) continue;
      for (const [name, node] of Object.entries(leaves)) {
        if (name.startsWith('$')) continue;
        const hex = modeHex(node, mode);
        if (group === 'color') {
          const cssName = CSS_VAR[`color.${name}`] || `--color-${name}`;
          lines.push(`  ${cssName}: ${hex};`);
          // card foreground tracks foreground in the original contract
          if (name === 'surface')
            lines.push(`  --card-foreground: ${modeHex(tokens.color.foreground, mode)};`);
          // `--muted` is the MUTED BACKGROUND (a dark surface), not the muted
          // foreground/text color. Map it to surface-raised so `bg-muted`
          // paints a real surface instead of aliasing `--muted-foreground`.
          if (name === 'surface-raised') lines.push(`  --muted: ${hex};`);
        } else if (group === 'radius') {
          lines.push(`  --radius-${name}: ${hex};`);
          if (name === 'lg') lines.push(`  --radius: ${hex};`);
        } else if (group === 'spacing') {
          lines.push(`  --space-${name}: ${hex};`);
        } else if (group === 'font') {
          if (node.$type === 'fontFamily') lines.push(`  --font-${name}: ${hex};`);
          else lines.push(`  --font-${name}: ${hex};`);
        } else if (group === 'motion') {
          if (node.$type === 'duration')
            lines.push(`  --motion-${name.replace('duration-', '')}: ${node.$value};`);
          else
            lines.push(
              `  --ease-${name.replace('easing-', '')}: cubic-bezier(${node.$value.join(', ')});`,
            );
        }
      }
    }
    lines.push('}');
    lines.push('');
  };
  emitMode('dark', ':root');
  emitMode('dark', '.dark');
  emitMode('light', '.light');
  return `${lines.join('\n')}\n`;
}

// --- Rust (mirrors apps/desktop/src/theme.rs named consts) ---
function buildRs() {
  const lines = [];
  lines.push('//! GENERATED by packages/design-tokens/scripts/build.mjs — do not edit.');
  lines.push('//! Vautr desktop colors, generated from tokens.json (dark theme).');
  lines.push('//! GPUI consumes raw Rgba; const-compatible (no fn calls in const).');
  lines.push('use gpui::Rgba;');
  lines.push('');
  lines.push('const fn c(hex: u32) -> Rgba {');
  lines.push('    Rgba {');
  lines.push('        r: ((hex >> 16) & 0xff) as f32 / 255.0,');
  lines.push('        g: ((hex >> 8) & 0xff) as f32 / 255.0,');
  lines.push('        b: (hex & 0xff) as f32 / 255.0,');
  lines.push('        a: 1.0,');
  lines.push('    }');
  lines.push('}');
  lines.push('const fn ca(hex8: u32, a: f32) -> Rgba {');
  lines.push('    Rgba {');
  lines.push('        r: ((hex8 >> 16) & 0xff) as f32 / 255.0,');
  lines.push('        g: ((hex8 >> 8) & 0xff) as f32 / 255.0,');
  lines.push('        b: (hex8 & 0xff) as f32 / 255.0,');
  lines.push('        a,');
  lines.push('    }');
  lines.push('}');
  lines.push('');
  // Map token -> Rust const name (matches existing theme.rs names where possible).
  const nameMap = {
    background: 'BG',
    surface: 'SURFACE',
    'surface-raised': 'SURFACE_RAISED',
    foreground: 'TEXT',
    'foreground-muted': 'TEXT_MUTED',
    'foreground-dim': 'TEXT_DIM',
    border: 'BORDER',
    accent: 'ACCENT',
    'accent-foreground': 'ACCENT_INK',
    'accent-dim': 'ACCENT_DIM',
    danger: 'DANGER',
    'danger-background': 'DANGER_BG',
    'danger-foreground': 'DANGER_TEXT',
    warning: 'WARN',
    success: 'SUCCESS',
  };
  for (const [name, node] of Object.entries(tokens.color)) {
    if (name.startsWith('$')) continue;
    const hex = modeHex(node, 'dark');
    const rust = nameMap[name] || name.toUpperCase().replace(/-/g, '_');
    if (hex.length === 9) {
      // #rrggbbaa -> split alpha
      const a = parseInt(hex.slice(7, 9), 16) / 255;
      lines.push(`pub const ${rust}: Rgba = ca(0x${hex.slice(1, 7)}, ${a.toFixed(3)});`);
    } else {
      lines.push(`pub const ${rust}: Rgba = c(0x${hex.slice(1)});`);
    }
  }
  lines.push('');
  return `${lines.join('\n')}\n`;
}

// --- TypeScript (mobile NativeWind theme) ---
function buildTs() {
  const lines = [];
  lines.push('// GENERATED by packages/design-tokens/scripts/build.mjs — do not edit.');
  lines.push('// Source of truth: tokens.json. Consumed by mobile/lib theme.');
  lines.push('export const tokens = {');
  for (const [group, leaves] of Object.entries(tokens)) {
    if (group.startsWith('$')) continue;
    lines.push(`  ${group}: {`);
    for (const [name, node] of Object.entries(leaves)) {
      if (name.startsWith('$')) continue;
      const v = node.$value;
      // JSON.stringify escapes inner quotes safely (font-family strings contain
      // double quotes like "Geist Variable"); arrays (cubicBezier) serialize too.
      const val = JSON.stringify(v);
      lines.push(`    "${name}": ${val},`);
    }
    lines.push('  },');
  }
  lines.push('};');
  lines.push('export type Tokens = typeof tokens;');
  lines.push('');
  return `${lines.join('\n')}\n`;
}

// --- GPUI theme JSON (regenerated from tokens + gpui-map) ---
function buildGpui() {
  const colors = {};
  for (const [key, target] of Object.entries(gpuiMap)) {
    if (key.startsWith('$')) continue;
    if (typeof target === 'string' && target.startsWith('{')) {
      colors[key] = modeHex(ref(target), 'dark');
    } else {
      colors[key] = target; // literal hex
    }
  }
  return `${JSON.stringify(
    {
      $schema:
        'https://github.com/longbridge/gpui-component/raw/refs/heads/main/.theme-schema.json',
      name: 'Vautr',
      author: 'Vautr',
      themes: [{ name: 'Vautr Dark', mode: 'dark', colors }],
    },
    null,
    2,
  )}\n`;
}

// --- Markdown swatches ---
function buildMd() {
  const lines = [];
  lines.push('# Vautr Design Tokens (generated)\n');
  lines.push(
    'Source: `tokens.json`. Regenerate with `pnpm --filter @vautr/design-tokens build:tokens`.\n',
  );
  lines.push('## Color\n');
  lines.push('| Token | Dark | Light |');
  lines.push('| --- | --- | --- |');
  for (const [name, node] of Object.entries(tokens.color)) {
    if (name.startsWith('$')) continue;
    lines.push(`| \`color.${name}\` | \`${node.$value.dark}\` | \`${node.$value.light}\` |`);
  }
  lines.push('');
  return lines.join('\n');
}

const outputs = {
  'tokens.css': buildCss(),
  'tokens.rs': buildRs(),
  'tokens.ts': buildTs(),
  'vautr-theme.json': buildGpui(),
  'tokens.md': buildMd(),
};

// App-side artifacts (committed, regenerated) so `cargo build` is self-sufficient
// and does not depend on the gitignored dist/. Paths are relative to repo root.
const REPO_ROOT = dirname(dirname(ROOT)); // packages/design-tokens -> repo root
const APP_ARTIFACTS = {
  'apps/desktop/src/theme_tokens.rs': outputs['tokens.rs'],
  'apps/desktop/src/vautr-theme.json': outputs['vautr-theme.json'],
};

let failed = false;
for (const [file, content] of Object.entries({ ...outputs, ...APP_ARTIFACTS })) {
  const base = file.startsWith('apps/') ? REPO_ROOT : ROOT;
  const outPath = join(base, file);
  if (CHECK) {
    if (!existsSync(outPath)) {
      console.error(`check:tokens FAIL — missing ${file}`);
      failed = true;
      continue;
    }
    const current = readFileSync(outPath, 'utf8');
    // Normalize whitespace so `cargo fmt` reformatting the generated Rust
    // artifact (or CSS/TS reflow) does not trip a false drift failure in a
    // node-only CI step. Real token-value changes still differ after
    // normalization.
    if (normalizeWs(current) !== normalizeWs(content)) {
      console.error(`check:tokens FAIL — ${file} is out of sync. Run build:tokens.`);
      failed = true;
    }
  } else {
    writeFileSync(outPath, content);
    console.log(`wrote ${file}`);
  }
}

if (!CHECK) {
  // Best-effort: keep the committed desktop Rust/JSON artifacts rustfmt-clean.
  try {
    spawnSync('cargo', ['fmt', '-p', 'vautr-desktop'], { cwd: REPO_ROOT, stdio: 'ignore' });
  } catch {
    /* no cargo toolchain in this environment — formatting is the dev's job */
  }
}

if (CHECK && failed) process.exit(1);
if (CHECK) console.log('check:tokens OK — all outputs in sync.');
