//! GENERATED by packages/design-tokens/scripts/build.mjs — do not edit.
//! Vautr desktop colors, generated from tokens.json (dark theme).
//! GPUI consumes raw Rgba; const-compatible (no fn calls in const).
use gpui::Rgba;

const fn c(hex: u32) -> Rgba {
    Rgba {
        r: ((hex >> 16) & 0xff) as f32 / 255.0,
        g: ((hex >> 8) & 0xff) as f32 / 255.0,
        b: (hex & 0xff) as f32 / 255.0,
        a: 1.0,
    }
}
const fn ca(hex8: u32, a: f32) -> Rgba {
    Rgba {
        r: ((hex8 >> 16) & 0xff) as f32 / 255.0,
        g: ((hex8 >> 8) & 0xff) as f32 / 255.0,
        b: (hex8 & 0xff) as f32 / 255.0,
        a,
    }
}

pub const BG: Rgba = c(0x080e16);
pub const TEXT: Rgba = c(0xe4ecf5);
pub const SURFACE: Rgba = c(0x0f151d);
pub const SURFACE_RAISED: Rgba = c(0x1e252e);
pub const TEXT_MUTED: Rgba = c(0x8f9aa4);
pub const TEXT_DIM: Rgba = c(0x6b7480);
pub const BORDER: Rgba = c(0x21272f);
pub const INPUT: Rgba = c(0x21272f);
pub const ACCENT: Rgba = c(0x42b59a);
pub const ACCENT_INK: Rgba = c(0x070e16);
pub const ACCENT_DIM: Rgba = ca(0x42b59a, 0.149);
pub const DANGER: Rgba = c(0xe85f61);
pub const DANGER_BG: Rgba = c(0x3c1517);
pub const DANGER_TEXT: Rgba = c(0xf2b4b5);
pub const WARN: Rgba = c(0xebb25f);
pub const SUCCESS: Rgba = c(0x37d59f);
pub const POPOVER: Rgba = c(0x131921);
pub const POPOVER_FOREGROUND: Rgba = c(0xe4ecf5);
pub const SIDEBAR: Rgba = c(0x0d1219);
pub const SIDEBAR_FOREGROUND: Rgba = c(0xe4ecf5);
pub const SIDEBAR_BORDER: Rgba = c(0x21272f);
pub const SIDEBAR_PRIMARY: Rgba = c(0x42b59a);
pub const SIDEBAR_PRIMARY_FOREGROUND: Rgba = c(0x070e16);
pub const SIDEBAR_ACCENT: Rgba = c(0x1e252e);
pub const SIDEBAR_ACCENT_FOREGROUND: Rgba = c(0xe4ecf5);
pub const RING: Rgba = c(0x42b59a);
pub const CHART_1: Rgba = c(0x42b59a);
pub const CHART_2: Rgba = c(0x3aa0c8);
pub const CHART_3: Rgba = c(0xe0b54a);
pub const CHART_4: Rgba = c(0x9a6fd0);
pub const CHART_5: Rgba = c(0xe57a6f);

