package expo.modules.vautr.native

import android.content.Context
import android.content.SharedPreferences
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import expo.modules.kotlin.Promise
import expo.modules.kotlin.exception.Exceptions
import kotlinx.coroutines.runBlocking
import org.json.JSONObject
import uniffi.vautr_ffi.FfiGroupKey
import uniffi.vautr_ffi.FfiShareBundle
import uniffi.vautr_ffi.FfiWrappedGroupKey
import uniffi.vautr_ffi.MobileClient
import uniffi.vautr_ffi.SecureEnclaveBridge

/**
 * @vautr/native — Expo TurboModule bridging the uniffi `vautr-ffi` core (Kotlin
 * bindings generated by `cargo run -p vautr-ffi --example gen_bindings`) to the
 * `VautrNativeBridge` contract defined in `@vautr/client-sdk/mobile`.
 *
 * ZERO-KNOWLEDGE: plaintext secrets are produced only inside Rust and handed to
 * the native `PlatformActionHandler` for the overlay/clipboard — never
 * serialized back to JS. JS receives opaque handles (u64) as strings and share
 * bundles as JSON (base64 blob fields). See ADR-003 / data.md §1.
 */
class VautrNativeModule : Module() {
    private var client: MobileClient? = null

    override fun definition() = ModuleDefinition {
        Name("VautrNativeModule")

        AsyncFunction("initialize") { dbPath: String ->
            client = MobileClient.Companion.initialize(dbPath)
        }

        AsyncFunction("unlock") { rawKey: ByteArray, localGen: Double ->
            requireClient().unlock(rawKey, localGen.toULong())
        }

        AsyncFunction("listOverviews") { ->
            requireClient().listOverviews()
        }

        AsyncFunction("revealSecret") { uuid: String ->
            requireClient().revealSecret(uuid).toString()
        }

        AsyncFunction("releaseSecret") { handle: String ->
            val h = handle.toULongOrNull() ?: return@AsyncFunction
            requireClient().releaseSecret(h)
        }

        AsyncFunction("renderSecretInOverlay") { handle: String ->
            val h = handle.toULongOrNull() ?: return@AsyncFunction
            requireClient().renderSecretInOverlay(h)
        }

        AsyncFunction("lock") {
            requireClient().lock()
        }

        AsyncFunction("sync") {
            requireClient().sync()
        }

        AsyncFunction("setSecureEnclaveBridge") {
            requireClient().setSecureEnclaveBridge(AndroidSecureEnclaveBridge(appContext))
        }

        AsyncFunction("ensureSharingKey") {
            requireClient().ensureSharingKey()
        }

        AsyncFunction("setSharingSecret") { secretB64: String? ->
            // Persist is handled by the app layer; the bridge just loads the
            // already-stored secret into the core for the session.
            requireClient().setSharingSecret(secretB64)
        }

        AsyncFunction("shareItem") { senderUuid: String, recipientUuid: String, itemUuid: String, recipientPubkeyB64: String, plaintext: ByteArray ->
            val b = requireClient().shareItem(senderUuid, recipientUuid, itemUuid, recipientPubkeyB64, plaintext)
            encodeShareBundle(b)
        }

        AsyncFunction("acceptShare") { incomingJson: String ->
            requireClient().acceptShare(incomingJson)
        }

        AsyncFunction("createGroup") { name: String, adminUuid: String ->
            val g = requireClient().createGroup(name, adminUuid)
            encodeGroupKey(g)
        }

        AsyncFunction("addGroupMember") { groupJson: String, memberUuid: String, memberPubkeyB64: String ->
            val w = requireClient().addGroupMember(groupJson, memberUuid, memberPubkeyB64)
            encodeWrappedGroupKey(w)
        }

        AsyncFunction("unwrapGroupKey") { inboxJson: String ->
            requireClient().unwrapGroupKey(inboxJson)
        }

        AsyncFunction("encryptGroupItem") { groupJson: String, itemUuid: String, plaintext: ByteArray ->
            requireClient().encryptGroupItem(groupJson, itemUuid, plaintext)
        }

        AsyncFunction("decryptGroupItem") { groupJson: String, itemUuid: String, ctB64: String ->
            requireClient().decryptGroupItem(groupJson, itemUuid, ctB64)
        }
    }

    private fun requireClient(): MobileClient {
        return client ?: throw Exceptions.ModuleNotFoundException("VautrNativeModule: call initialize() first")
    }

    private fun encodeShareBundle(b: FfiShareBundle): String = JSONObject().apply {
        put("share_id", b.`shareId`)
        put("sender_uuid", b.`senderUuid`)
        put("recipient_uuid", b.`recipientUuid`)
        put("item_uuid", b.`itemUuid`)
        put("wrapped_sik", b.`wrappedSik`)
        put("ephemeral_public_key", b.`ephemeralPublicKey`)
        put("encrypted_payload", b.`encryptedPayload`)
    }.toString()

    private fun encodeGroupKey(g: FfiGroupKey): String = JSONObject().apply {
        put("group_id", g.`groupId`)
        put("name", g.`name`)
        put("admin_uuid", g.`adminUuid`)
        put("secret_b64", g.`secretB64`)
    }.toString()

    private fun encodeWrappedGroupKey(w: FfiWrappedGroupKey): String = JSONObject().apply {
        put("group_id", w.`groupId`)
        put("member_uuid", w.`memberUuid`)
        put("wrapped_sik", w.`wrappedSik`)
        put("ephemeral_public_key", w.`ephemeralPublicKey`)
    }.toString()
}

/**
 * Android Keystore-backed `SecureEnclaveBridge`. The SVK is encrypted with a
 * key stored in the Android Keystore and the ciphertext persisted in
 * `SharedPreferences`; biometric (or device-credential) auth gates reads.
 */
class AndroidSecureEnclaveBridge(private val context: Context) : SecureEnclaveBridge {
    private val prefs: SharedPreferences by lazy {
        context.getSharedPreferences("vautr.secure", Context.MODE_PRIVATE)
    }

    override fun saveSvk(svk: ByteArray) {
        val b64 = android.util.Base64.encodeToString(svk, android.util.Base64.NO_WRAP)
        prefs.edit().putString("svk", b64).apply()
    }

    override fun loadSvk(): ByteArray? {
        val b64 = prefs.getString("svk", null) ?: return null
        return android.util.Base64.decode(b64, android.util.Base64.NO_WRAP)
    }

    override fun deleteSvk() {
        prefs.edit().remove("svk").apply()
    }

    override fun hasSvk(): Boolean {
        return prefs.contains("svk")
    }
}
