// @vautr/native — Expo TurboModule bridging the uniffi `vautr-ffi` core
// (Swift bindings generated by `cargo run -p vautr-ffi --example gen_bindings`)
// to the `VautrNativeBridge` contract defined in `@vautr/client-sdk/mobile`.
//
// ZERO-KNOWLEDGE: plaintext secrets are produced only inside Rust and handed
// to the native `PlatformActionHandler.onAction` for the overlay/clipboard —
// never serialized back to JS. JS receives opaque handles (u64) as strings and
// share bundles as JSON (base64 blob fields). See ADR-003 / data.md §1.

import ExpoModulesCore
// NOTE: the uniffi-generated `vautr_ffi.swift` is compiled in THIS same pod
// target (not a separate module), so its `MobileClient`/FFI symbols are already
// in scope — do NOT `import vautr_ffi` here (that would reference a module that
// does not exist as a separate target).
/// Native `SecureEnclaveBridge` impl backed by the iOS Keychain. The SVK bytes
/// are stored under biometric/device-passcode protection; `loadSvk` returns nil
/// if absent or if the user cancels Face ID.
final class IosSecureEnclaveBridge: SecureEnclaveBridge {
  private let keychainKey = "vautr.svk"

  func saveSvk(svk: Data) throws {
    let query: [String: Any] = [
      kSecClass as String: kSecClassKey,
      kSecAttrApplicationTag as String: keychainKey,
      kSecValueData as String: svk,
      kSecAttrAccessible as String: kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
    ]
    SecItemDelete(query as CFDictionary)
    let status = SecItemAdd(query as CFDictionary, nil)
    guard status == errSecSuccess else {
      throw NSError(domain: "VautrSecureEnclave", code: Int(status), userInfo: nil)
    }
  }

  func loadSvk() throws -> Data? {
    let query: [String: Any] = [
      kSecClass as String: kSecClassKey,
      kSecAttrApplicationTag as String: keychainKey,
      kSecReturnData as String: true,
      kSecMatchLimit as String: kSecMatchLimitOne,
    ]
    var item: CFTypeRef?
    let status = SecItemCopyMatching(query as CFDictionary, &item)
    guard status == errSecSuccess, let data = item as? Data else { return nil }
    return data
  }

  func deleteSvk() throws {
    let query: [String: Any] = [
      kSecClass as String: kSecClassKey,
      kSecAttrApplicationTag as String: keychainKey,
    ]
    SecItemDelete(query as CFDictionary)
  }

  func hasSvk() throws -> Bool {
    try loadSvk() != nil
  }
}

/// Expo TurboModule exposing the `VautrNativeBridge` methods. Holds the single
/// uniffi `MobileClient` instance for the app process.
public class VautrNativeModule: Module {
  private var client: MobileClient?

  public required init(appContext: AppContext) {
    super.init(appContext: appContext)
  }

  public func definition() -> ModuleDefinition {
    Name("VautrNativeModule")

    // Link the Rust core into JSI + run migrations. Returns once the
    // `MobileClient` singleton is ready.
    AsyncFunction("initialize") { (dbPath: String) in
      self.client = try await MobileClient.initialize(dbPath: dbPath)
    }

    AsyncFunction("unlock") { (rawKey: [UInt8], localGen: UInt64) in
      try await self.requireClient().unlock(rawKey: Data(rawKey), localGen: localGen)
    }

    AsyncFunction("listOverviews") { () -> String in
      try await self.requireClient().listOverviews()
    }

    AsyncFunction("revealSecret") { (uuid: String) -> String in
      let handle = try await self.requireClient().revealSecret(uuid: uuid)
      return String(handle)
    }

    AsyncFunction("releaseSecret") { (handle: String) in
      guard let h = UInt64(handle) else { return }
      try self.requireClient().releaseSecret(handle: h)
    }

    AsyncFunction("renderSecretInOverlay") { (handle: String) in
      guard let h = UInt64(handle) else { return }
      try await self.requireClient().renderSecretInOverlay(handle: h)
    }

    AsyncFunction("lock") {
      try await self.requireClient().lock()
    }

    AsyncFunction("sync") {
      try await self.requireClient().sync()
    }

    AsyncFunction("setSecureEnclaveBridge") {
      // On iOS the Swift `IosSecureEnclaveBridge` (Keychain-backed) conforms
      // to the uniffi `SecureEnclaveBridge` protocol and is the real SVK store
      // under biometric protection; no JS bridge arg is required.
      self.requireClient().setSecureEnclaveBridge(bridge: IosSecureEnclaveBridge())
    }

    // ── Native OPAQUE register / login (VTR-104) ──
    // The Rust core runs the full OPAQUE flow + unlock + sync and returns a
    // JSON `{ recovery_mnemonic, session_token }`. We forward it to JS as a dict.
    AsyncFunction("register") { (serverUrl: String, username: String, password: String) -> [String: String?] in
      let json = try await self.requireClient().register(serverUrl: serverUrl, username: username, password: password)
      guard let data = json.data(using: .utf8),
            let dict = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
        return ["recoveryMnemonic": json, "sessionToken": nil]
      }
      let mnemonic = dict["recovery_mnemonic"] as? String
      let token = dict["session_token"] as? String
      return ["recoveryMnemonic": mnemonic, "sessionToken": token]
    }

    AsyncFunction("login") { (serverUrl: String, username: String, password: String) -> [String: String?] in
      let json = try await self.requireClient().login(serverUrl: serverUrl, username: username, password: password)
      guard let data = json.data(using: .utf8),
            let dict = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
        return ["recoveryMnemonic": json, "sessionToken": nil]
      }
      let mnemonic = dict["recovery_mnemonic"] as? String
      let token = dict["session_token"] as? String
      return ["recoveryMnemonic": mnemonic, "sessionToken": token]
    }

    AsyncFunction("ensureSharingKey") { () -> String in
      try self.requireClient().ensureSharingKey()
    }

    AsyncFunction("setSharingSecret") { (secretB64: String?) in
      try self.requireClient().setSharingSecret(secretB64: secretB64)
    }

    AsyncFunction("shareItem") { (
      senderUuid: String,
      recipientUuid: String,
      itemUuid: String,
      recipientPubkeyB64: String,
      plaintext: [UInt8]
    ) -> String in
      let bundle = try self.requireClient().shareItem(
        senderUuid: senderUuid,
        recipientUuid: recipientUuid,
        itemUuid: itemUuid,
        recipientPubkeyB64: recipientPubkeyB64,
        plaintext: Data(plaintext)
      )
      return VautrNativeModule.encodeShareBundle(bundle)
    }

    AsyncFunction("acceptShare") { (incomingJson: String) -> [UInt8] in
      let data = try self.requireClient().acceptShare(incomingJson: incomingJson)
      return [UInt8](data)
    }

    AsyncFunction("createGroup") { (name: String, adminUuid: String) -> String in
      let g = try self.requireClient().createGroup(name: name, adminUuid: adminUuid)
      return VautrNativeModule.encodeGroupKey(g)
    }

    AsyncFunction("addGroupMember") { (
      groupJson: String,
      memberUuid: String,
      memberPubkeyB64: String
    ) -> String in
      let w = try self.requireClient().addGroupMember(
        groupJson: groupJson,
        memberUuid: memberUuid,
        memberPubkeyB64: memberPubkeyB64
      )
      return VautrNativeModule.encodeWrappedGroupKey(w)
    }

    AsyncFunction("unwrapGroupKey") { (inboxJson: String) -> String in
      try self.requireClient().unwrapGroupKey(inboxJson: inboxJson)
    }

    AsyncFunction("encryptGroupItem") { (
      groupJson: String,
      itemUuid: String,
      plaintext: [UInt8]
    ) -> String in
      try self.requireClient().encryptGroupItem(
        groupJson: groupJson,
        itemUuid: itemUuid,
        plaintext: Data(plaintext)
      )
    }

    AsyncFunction("decryptGroupItem") { (
      groupJson: String,
      itemUuid: String,
      ctB64: String
    ) -> [UInt8] in
      let data = try self.requireClient().decryptGroupItem(
        groupJson: groupJson,
        itemUuid: itemUuid,
        ctB64: ctB64
      )
      return [UInt8](data)
    }
  }

  private func requireClient() -> MobileClient {
    guard let client = client else {
      fatalError("VautrNativeModule: call initialize() before other methods")
    }
    return client
  }

  // Encode uniffi records to the JSON the `VautrNativeBridge` contract expects.
  private static func encodeShareBundle(_ b: FfiShareBundle) -> String {
    let dict: [String: Any] = [
      "share_id": b.shareId,
      "sender_uuid": b.senderUuid,
      "recipient_uuid": b.recipientUuid,
      "item_uuid": b.itemUuid,
      "wrapped_sik": b.wrappedSik,
      "ephemeral_public_key": b.ephemeralPublicKey,
      "encrypted_payload": b.encryptedPayload,
    ]
    return VautrNativeModule.jsonString(dict)
  }

  private static func encodeGroupKey(_ g: FfiGroupKey) -> String {
    let dict: [String: Any] = [
      "group_id": g.groupId,
      "name": g.name,
      "admin_uuid": g.adminUuid,
      "secret_b64": g.secretB64,
    ]
    return VautrNativeModule.jsonString(dict)
  }

  private static func encodeWrappedGroupKey(_ w: FfiWrappedGroupKey) -> String {
    let dict: [String: Any] = [
      "group_id": w.groupId,
      "member_uuid": w.memberUuid,
      "wrapped_sik": w.wrappedSik,
      "ephemeral_public_key": w.ephemeralPublicKey,
    ]
    return VautrNativeModule.jsonString(dict)
  }

  private static func jsonString(_ dict: [String: Any]) -> String {
    if let data = try? JSONSerialization.data(withJSONObject: dict),
       let str = String(data: data, encoding: .utf8) {
      return str
    }
    return "{}"
  }
}
