/*
 * VTR-048 — Native secret overlay (Android / Kotlin).
 *
 * Design (ADR-003): the plaintext secret NEVER enters the JS/Kotlin heap via
 * the React Native bridge. The JS layer only ever holds an opaque `u64` handle
 * (surfaced as a `String`). When the Detail screen wants to show a secret, it
 * calls `renderInOverlay(handle)` on the Turbo Module, which asks the Rust core
 * to delegate `PlatformActionHandler.onAction(RenderInOverlay, secret)` to the
 * native handler below. This Kotlin code receives the plaintext string directly
 * from Rust (not from JS) and renders it in a `TextView`.
 *
 * Memory hygiene: the overlay registers a callback that calls `releaseSecret`
 * (which zeroizes the in-memory secret in Rust) when the view is detached
 * (`onDetachedFromWindow`) or when the host fragment/activity is destroyed —
 * satisfying the "zeroized on unmount" acceptance criterion (TDD3).
 *
 * NOTE: `VautrClient`, `CoreAction`, `PlatformActionHandler` and `OpaqueHandle`
 * are generated by UniFFI 0.31 from `core/vautr-ffi` (the `VautrNativeBridge`
 * contract in `packages/vautr-client-sdk/src/mobile.ts`). They are present once
 * the uniffi Kotlin bindings are generated into this module; this file is the
 * native consumer of that contract.
 */

package io.vautr.mobile.secret

import android.content.Context
import android.util.AttributeSet
import android.view.View
import android.widget.TextView
import io.vautr.mobile.ffi.CoreAction
import io.vautr.mobile.ffi.PlatformActionHandler
import io.vautr.mobile.ffi.VautrClient
import io.vautr.mobile.ffi.OpaqueHandle

/**
 * A native view that displays a revealed secret. The plaintext is supplied only
 * by [setSecret] (called from the native [PlatformActionHandler.onAction]),
 * never from JS. The view owns a reference to the active handle so it can
 * release it on detach.
 */
class NativeSecretView @JvmOverloads constructor(
    context: Context,
    attrs: AttributeSet? = null,
    defStyle: Int = 0,
) : TextView(context, attrs, defStyle) {

    /** Opaque handle for the currently displayed secret (u64 as String). */
    private var activeHandle: OpaqueHandle? = null

    /** The Rust client used to release the handle on unmount. */
    var client: VautrClient? = null

    /** Render `secret` for the given opaque `handle`. Called from native only. */
    fun setSecret(handle: OpaqueHandle, secret: String) {
        activeHandle = handle
        text = secret
        // Secret is now on screen; the String is owned by this view's text
        // buffer and is overwritten/GC'd when the next value is set or the
        // view is detached. We do NOT log it or copy it anywhere.
    }

    override fun onDetachedFromWindow() {
        super.onDetachedFromWindow()
        releaseActiveSecret()
    }

    /**
     * Release the active handle, zeroizing the in-memory secret in Rust (TDD3).
     * Safe to call multiple times; the Rust side rejects an already-released
     * handle.
     */
    fun releaseActiveSecret() {
        val handle = activeHandle ?: return
        activeHandle = null
        text = ""
        client?.releaseSecret(handle)
    }
}

/**
 * Native `PlatformActionHandler` implementation registered with the Rust core
 * (via `MobileClient.setPlatformHandler`). The core calls [onAction] with the
 * decrypted plaintext — for [CoreAction.RenderInOverlay] we push it into the
 * [NativeSecretView] this handler drives (TDD1).
 */
class SecretOverlayActionHandler(
    private val overlay: NativeSecretView,
) : PlatformActionHandler {

    override fun onAction(action: CoreAction, secret: String) {
        when (action) {
            is CoreAction.RenderInOverlay -> {
                // Plaintext delivered by Rust directly to native — never JS.
                overlay.setSecret(action.handle, secret)
            }
            is CoreAction.CopyToClipboard -> {
                // Clipboard path handled elsewhere; ignore here.
            }
            is CoreAction.Autofill -> {
                // Autofill path handled elsewhere; ignore here.
            }
        }
    }
}
