// boneyard bone registry (VTR: loading-skeleton UI via github.com/0xGF/boneyard).
//
// Generated by `npx boneyard-js build` once a dev server / browser is available.
// Until then this is an intentional no-op placeholder so the `import
// './bones/registry'` in main.tsx resolves and <Skeleton> gracefully falls back
// to its `fallback` prop (the original <p>Loading…</p> node) when no bones
// have been captured yet. Capture is a dev-only step; production ships the
// generated .bones.json + this registry unchanged.
export {};
