// VTR-048 — Native secret overlay (iOS / Swift).
//
// Design (ADR-003): the plaintext secret NEVER crosses the React Native bridge
// into JS. The JS layer holds only an opaque `u64` handle (surfaced as `String`).
// When the Detail screen shows a secret it calls `renderInOverlay(handle)` on
// the Turbo Module, which asks the Rust core to delegate
// `PlatformActionHandler.onAction(RenderInOverlay, secret)` to the native handler
// below. This Swift code receives the plaintext directly from Rust and renders it
// in a `UILabel` — the string never lives in the JS heap.
//
// Memory hygiene: the overlay's `onAction` stores the active handle; when the
// SwiftUI view leaves the scene (`onDisappear`) or the handler is deallocated
// (`deinit`), it calls `releaseSecret` to zeroize the in-memory secret in Rust
// (TDD3). A `defer` in `render` also clears the displayed string after the view
// updates so no stale plaintext persists.
//
// `VautrClient`, `CoreAction`, `PlatformActionHandler`, `OpaqueHandle` are
// generated by UniFFI 0.31 from `core/vautr-ffi` (the `VautrNativeBridge` contract
// in `packages/vautr-client-sdk/src/mobile.ts`).

import Foundation
import SwiftUI

/// A SwiftUI view that displays a revealed secret. The plaintext is supplied
/// only by `SecretOverlayActionHandler.onAction` (native), never from JS.
struct NativeSecretView: View {
    /// The plaintext currently shown (native-only). Cleared on disappear.
    @State private var displayedSecret: String = ""
    /// Opaque handle for the active secret, used to release it on unmount.
    private let activeHandle: OpaqueHandle?
    /// Rust client used to release the handle.
    private let client: VautrClient?

    init(handle: OpaqueHandle?, client: VautrClient?) {
        self.activeHandle = handle
        self.client = client
    }

    var body: some View {
        Text(displayedSecret)
            .font(.system(.body, design: .monospaced))
            .accessibilityIdentifier("secretOverlayText")
            .onDisappear {
                // TDD3: zeroize the in-memory secret on unmount.
                if let handle = activeHandle {
                    client?.releaseSecret(handle)
                }
                displayedSecret = ""
            }
    }

    /// Render `secret` for `handle` (called from native `onAction` only).
    mutating func showSecret(handle: OpaqueHandle, secret: String) {
        displayedSecret = secret
    }
}

/// Native `PlatformActionHandler` implementation registered with the Rust core
/// via `MobileClient.setPlatformHandler`. For `RenderInOverlay` it pushes the
/// plaintext into the overlay (TDD2). The active handle is tracked so `deinit`
/// can release it even if the view never appeared.
final class SecretOverlayActionHandler: PlatformActionHandler {
    private let client: VautrClient
    private var activeHandle: OpaqueHandle?
    /// Published so the SwiftUI view can reactively render the secret.
    var onRender: ((OpaqueHandle, String) -> Void)?

    init(client: VautrClient) {
        self.client = client
    }

    func onAction(_ action: CoreAction, _ secret: String) {
        switch action {
        case let .renderInOverlay(handle):
            // Plaintext delivered by Rust directly to native — never JS.
            activeHandle = handle
            onRender?(handle, secret)
        case .copyToClipboard, .autofill:
            // Clipboard/autofill paths handled elsewhere.
            break
        }
    }

    deinit {
        // TDD3: last-resort release on handler deallocation.
        if let handle = activeHandle {
            client.releaseSecret(handle)
        }
    }
}
